# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZazCar' do

pod 'AFNetworking', '~> 3.0'
pod 'UIScrollView-InfiniteScroll'
pod 'ObjectMapper', '~> 1.2'
pod 'Alamofire', '~> 3.3'
pod 'AlamofireImage', '~> 2.0'
pod 'UIColor_Hex_Swift', '~> 2.0'
pod 'KRProgressHUD'
end

